export { default as IconBot } from './icon-bot'
export { default as IconSettings } from './icon-settings'
export { default as IconChart } from './icon-chart'
export { default as IconOpen } from './icon-open'
export { default as IconPage } from './icon-page'
